chore(example): update tsconfig in music-library
- Upgraded TypeScript target to ES6
- Added deprecation ignore flag
- avoid errors like:
  - `ERROR TS5107: Option 'target=ES5' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption '"ignoreDeprecations": "6.0"' to silence this error.`
  - `ERROR TS5101: Option 'downlevelIteration' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption '"ignoreDeprecations": "6.0"' to silence this error.`
- subscribed corresponding isse: https://github.com/cypress-io/cypress/issues/33385